# -*- coding: utf-8 -*-
"""Group fairness in IM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qGZjQdATKaxJNd1KhuGSHIk1tk5HQV_
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/bwilder0/fair_influmax_code_release.git
# %cd fair_influmax_code_release

!ls

"""fix old version - change every instance of g.node[v][attribute] to g.nodes[v][attribute]"""

!grep -rn '\.node\[' /content/fair_influmax_code_release --include=*.py

!grep -rl '\.node\[' /content/fair_influmax_code_release --include=*.py | xargs sed -i 's/\.node\[/.nodes[/g'

!grep -rn '\.node\[' /content/fair_influmax_code_release --include=*.py

"""fix old version - change every instance of np.int to int"""

!grep -rn 'np\.\(int\|float\|bool\|object\)\b' /content/fair_influmax_code_release --include=*.py

!grep -rl 'np\.int\b' /content/fair_influmax_code_release --include=*.py | xargs sed -i 's/np\.int\b/int/g'

!grep -rn 'np\.\(int\|float\|bool\|object\)\b' /content/fair_influmax_code_release --include=*.py

!sed -i \
  -e 's/val_oracle(x, 1000)/val_oracle(x, 200)/' \
  -e 's/val_oracle((1\/num_iter)\*x\[0:t\].sum(axis=0), 5000)/val_oracle((1\/num_iter)*x[0:t].sum(axis=0), 500)/' \
  -e 's/num_iter=1000/num_iter=200/' \
  -e 's/val_oracle(x.mean(axis=0), 1000)/val_oracle(x.mean(axis=0), 200)/' \
  /content/fair_influmax_code_release/algorithms.py

!grep -n '200\|500' /content/fair_influmax_code_release/algorithms.py

"""with budget = 15"""

!python check_fairness.py

"""with budget = 25"""

!python check_fairness.py

"""Install **GUROBI**"""

!pip install gurobipy==13.0.2

!wget https://packages.gurobi.com/13.0/gurobi13.0.2_linux64.tar.gz -O gurobi.tar.gz
!ls -la gurobi.tar.gz

!ls -la gurobi.tar.gz
!tar tzf gurobi.tar.gz | head -30

!tar xzf gurobi.tar.gz
!ls gurobi1302/linux64/bin/